services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    # Enlaza el puerto 8000 del contenedor con el 8000 de tu host
    ports:
      - "8000:8000"
    # Monta un volumen para que el archivo estacionamiento.db se persista
    volumes:
      - estacionamiento_data:/app
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    # Enlaza el puerto 3000 del contenedor con el 3000 de tu host
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    restart: always

volumes:
  estacionamiento_data:
